# Generated by Django 2.0.9 on 2018-10-21 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerPriceIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('all_fields', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shelter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transportation', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
