# Generated by Django 2.0.9 on 2018-10-21 01:46

from django.conf import settings
from django.db import migrations

import csv


DEFAULT_PATH = str(settings.APPS_DIR.path('indicators').path('consumer_price_indexes.csv'))


def _import_csv_consumer_price_indexes(path=DEFAULT_PATH):
    result = {}

    with open(path, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        result = []
        for row in reader:
            result.append({
                'date': row['Reference period'],
                'all_fields': row['All-items'],
                'food': row['Food'],
                'shelter': row['Shelter'],
                'transportation': row['Transportation']
            })

    return result


def create_instances(apps, schema_editor):
    ConsumerPriceIndex = apps.get_model('indicators', 'ConsumerPriceIndex')
    indexes = _import_csv_consumer_price_indexes()

    ConsumerPriceIndex.objects.bulk_create([
        ConsumerPriceIndex(
            date=index['date'],
            all_fields=index['all_fields'],
            food=index['food'],
            shelter=index['shelter'],
            transportation=index['transportation']
        ) for index in indexes]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=create_instances, reverse_code=migrations.operations.special.RunPython.noop,),
    ]
